### ISSUE TITLE
v1.4 checklist

### ISSUE THREAD

**Issue by dndrks** [dndrks/cheat_codes#48]
- [ ] add bound mode to grid/arc pattern params
- [ ] arc encoder 4: record head manipulation
- [ ] loose patterns w/bar awareness
- [ ] one-shot patterns
- [ ] pattern quantize start resolution
