### ISSUE TITLE
tracker

### ISSUE THREAD

**Issue by dndrks** [dndrks/cheat_codes#52]
### control
- [x] K1 + K3 on top row == start/stop
- [x] should transport be beat-synced?

### columns
- [ ] `random` option that just chooses a new value every time?
- [ ] add `*` option to pad selector, to indicate no change to pad (parameter jump, applies to softcut directly)

### pad menu
- [ ] K3 will execute the current parameters
- [ ] rate
- [ ] buffer
- [ ] filter tilt
- [ ] level
- [ ] delay send
- [ ] start point
- [ ] end point
- [ ] panning
- [ ] re-trigger

### 4th page

- [ ] construct tracker from keyboard
- [ ] construct tracker from grid
- [ ] construct tracker from arp
- [x] construct tracker from snake/included patterns
- [ ] define tracker crawl behavior:
     - [ ] linear (start -> end)
     - [ ] reverse (end -> start)
     - [ ] ping-pong (start -> end -> start)
     - [ ] random

**Comment by dndrks** [comment]
not now.
