### ISSUE TITLE
the chill-the-hell-out checklist

### ISSUE THREAD

**Issue by dndrks** [dndrks/cheat_codes#57]
- [x] hide trkr for now
- [x] grid alt + bank-alt: latch bank-alt
- [x] bank-alt is momentary unless latched
- [x] grid-alt works like OG way as well
- [x] midi pattern recorder
- [x] give 'em longer sample import, at least
- [x] arc controls panning + levels
